// Tests for CoreDiffDomain, driven by the golden fixtures in `Fixtures/`.
//
// The fixtures are generated by `Scripts/make-fixture-repo.sh` running the real git binary, and
// the resulting `.diff` files are committed — so the parser suite also runs on a machine with no
// git, and a change in git's output shows up as a fixture diff rather than as a silent drift.
